# .github/workflows/deploy.yml
name: Fly Deploy

on:
  workflow_run:
    workflows: ["Run Tests"] # Asegúrate de que coincida con el nombre del workflow de tests
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Solo ejecuta si los tests pasaron
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # Asegura que solo se ejecute una acción de despliegue a la vez
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
